### PR TITLE
MarDI Feature Request Template

### PR DESCRIPTION
**Pull request by Hyper-Node**
# MaRDI Pull Request
(this template is to be filled out by the person who is creating the pull-request)

**Goal**: 
(bigger goal you want to achieve with this PR)
-  Introduce feature-request template 
- 

**Changes**:
(summary of the basic changes to the source-files within this PR)
- new file for feature request template
- 
-  

**Instructions for PR review**:
(these are marked by the person creating the PR and should be checked by the reviewer) 
- Please Review Template and make changed suggestions  in comment if necessary. 

**Checklist for this PR**: 
- [x] At least one reviewer has been assigned. 
- [x] All related issues with further descriptions are linked.

Workaround for referencing non-repository-issues: 
MaRDI4NFDI/T5ProjectManagement#31

### CODE REVIEW

**Comment by Hyper-Node** [comment]
https://github.com/MaRDI4NFDI/T5ProjectManagement/issues/31

**Comment by Hyper-Node** [comment]
user/repository#number

MaRDI4NFDI/T5ProjectManagement/#31

**Comment by Hyper-Node** [comment]
@aot29 if there are no changes suggested, i consider this done and will merge.

**Comment by aot29** [comment]
OK

**Pull request merged**
